name: Add team label
description: Add team labels to new pull requests
author: Richard Macklin
inputs:
  repo_token:
    required: true
    description: >
      This token will be used to authenticate to GitHub when adding labels to
      your pull requests.
runs:
  using: node12
  main: dist/index.js
